spring:
  application:
     name: cli-service

shell:
  out:
    info: CYAN
    success: GREEN
    warning: YELLOW
    error: RED
    
server.port: 5555
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10   # DO NOT DO THIS IN PRODUCTION

logging:
  file: "logs/console.log"